<!DOCTYPE html>
<html>

<head>

    <title>Phire CMS : <?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php if (count($assets['js']) > 0): ?>
<?php foreach ($assets['js'] as $js): ?>
    <script type="text/javascript" src="<?=$js; ?>"></script>
<?php endforeach; ?>
<?php endif; ?>

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
<?php if (count($assets['css']['link']) > 0): ?>
<?php foreach ($assets['css']['link'] as $css): ?>
    <link type="text/css" rel="stylesheet" href="<?=$css; ?>" />
<?php endforeach; ?>
<?php endif; ?>

<?php if (count($assets['css']['import']) > 0): ?>
    <style type="text/css">
<?php foreach ($assets['css']['import'] as $css): ?>
        @import url('<?=$css; ?>');
<?php endforeach; ?>
    </style>
<?php endif; ?>

    <link rel="shortcut icon" href="<?=$contentPath; ?>/assets/phire/img/phire-icon.png" type="image/png" />

<?php
    $click = ($_GET['editor'] == 'ckeditor') ?
        'window.opener.CKEDITOR.tools.callFunction(funcNum, this.href); window.close(); return false;' :
        'top.tinymce.activeEditor.windowManager.getParams().oninsert(this.href); top.tinymce.activeEditor.windowManager.close(); return false;';
?>
<?php if ($_GET['editor'] == 'ckeditor'): ?>
    <script type="text/javascript">
        function getUrlParam(paramName) {
            var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i');
            var match = window.location.search.match(reParam);
            return (match && match.length > 1) ? match[1] : '';
        }
        var funcNum = getUrlParam('CKEditorFuncNum');
    </script>
<?php endif; ?>

</head>

<body>
<div id="browser-container">
    <header>
        <h1 class="browser-title"><?=$title; ?></h1>
        <a class="logo">Home</a>
    </header>
    <div id="browser-content">
<?php if (isset($libraries) && (count($libraries) > 0)): ?>
<?php foreach ($libraries as $library => $types): ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><?=$library; ?></th>
            </tr>
<?php foreach ($types as $id => $type): ?>
            <tr>
                <td><a href="<?=$_SERVER['REQUEST_URI'] . '&asset=' . $id; ?>"><?=$type; ?></a></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php endforeach; ?>
<?php elseif (isset($browserAssets) && (count($browserAssets) > 0)): ?>
<?php if (isset($assetType)): ?>
    <h3><?=$assetType; ?></h3>
<?php endif; ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th>&nbsp;</th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($browserAssets as $asset => $name): ?>
            <tr>
                <td><a href="<?=$asset; ?>" onclick="<?=$click; ?>"><?=$name; ?></a></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php else: ?>
    <p>There are currently no assets.</p>
<?php endif; ?>
    </div>
</div>
</body>

</html>