<?php include $phireHeader; ?>
    <h1 class="fields-header"><?=$title; ?> : <span id="title-span"><?=$field_group_name; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'field-groups', 'add')): ?>
        <nav><a href="<?=$phireUri . '/fields/groups/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/fields/groups'; ?>">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
