<?php include $phireHeader; ?>
    <h1 class="fields-header"><?=$title; ?></h1>
<?php if (count($groups) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'field-groups', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri . '/fields/groups/add'; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'field-groups', 'remove')): ?>
    <form id="field-groups-form" action="<?=$phireUri . '/fields/groups/remove'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/fields/groups?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/fields/groups?sort=name';?>">Name</a></th>
                <th><a href="<?=$phireUri . '/fields/groups?sort=order';?>">Order</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'field-groups', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'field-groups', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_groups" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($groups as $group): ?>
            <tr>
                <td><?=$group->id; ?></td>
                <td><?=$group->name; ?></td>
                <td><?=(($group->order) ? 'Yes' : 'No'); ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'field-groups', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/fields/groups/edit/' . $group->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'field-groups', 'remove')): ?><input type="checkbox" name="rm_groups[]" id="rm_groups<?=$i++; ?>" value="<?=$group->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'field-groups', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
<?php if ($acl->isAllowed($user->role, 'field-groups', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri . '/fields/groups/add'; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
    <p>There are currently no field groups.</p>
<?php endif; ?>
<?php include $phireFooter; ?>